export const types = {
  FETCH_MEDIA_START: '[MEDIA] FETCH_MEDIA_START',
  FETCH_MEDIA_SUCCESS: '[MEDIA] FETCH_MEDIA_SUCCESS',
  FETCH_MEDIA_DETAILS_SUCCESS: '[MEDIA] FETCH_MEDIA_DETAILS_SUCCESS',
  FETCH_MEDIA_FAIL: '[MEDIA] FETCH_MEDIA_FAIL',
};
